# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/circuit_analysis.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/circuit_analysis.proto',
  package='bigspicy',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cproto/circuit_analysis.proto\x12\x08\x62igspicy\")\n\x03Net\x12\x13\n\x0bsignal_name\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x04\"-\n\x0fSimulatedDriver\x12\x1a\n\x03net\x18\x01 \x01(\x0b\x32\r.bigspicy.Net\"=\n\x0e\x43\x61pacitiveLoad\x12\x1a\n\x03net\x18\x01 \x01(\x0b\x32\r.bigspicy.Net\x12\x0f\n\x07value_f\x18\x02 \x01(\x01\"$\n\x06\x44\x43\x42ias\x12\x1a\n\x03net\x18\x01 \x01(\x0b\x32\r.bigspicy.Net\"*\n\x0cVoltageProbe\x12\x1a\n\x03net\x18\x01 \x01(\x0b\x32\r.bigspicy.Net\"F\n\x0c\x41nalysisPort\x12\x1a\n\x03net\x18\x01 \x01(\x0b\x32\r.bigspicy.Net\x12\x1a\n\x12load_capacitance_f\x18\x02 \x01(\x01\"\x9e\x03\n\x0c\x44\x65signRegion\x12\x0c\n\x04name\x18\x01 \x01(\t\x12<\n\x08\x64ut_type\x18\x02 \x01(\x0e\x32*.bigspicy.DesignRegion.DeviceUnderTestType\x12\x16\n\x0e\x66or_top_module\x18\x03 \x01(\t\x12\x11\n\tinstances\x18\x04 \x03(\t\x12#\n\tdc_biases\x18\x05 \x03(\x0b\x32\x10.bigspicy.DCBias\x12\'\n\x05loads\x18\x06 \x03(\x0b\x32\x18.bigspicy.CapacitiveLoad\x12*\n\x07\x64rivers\x18\x07 \x03(\x0b\x32\x19.bigspicy.SimulatedDriver\x12.\n\x0evoltage_probes\x18\x08 \x03(\x0b\x32\x16.bigspicy.VoltageProbe\x12%\n\x05ports\x18\t \x03(\x0b\x32\x16.bigspicy.AnalysisPort\"F\n\x13\x44\x65viceUnderTestType\x12\x0e\n\nSUB_REGION\x10\x00\x12\n\n\x06MODULE\x10\x01\x12\x13\n\x0f\x45XTERNAL_MODULE\x10\x02\"A\n\x0f\x43ircuitAnalysis\x12.\n\x0e\x64\x65sign_regions\x18\x01 \x03(\x0b\x32\x16.bigspicy.DesignRegionb\x06proto3'
)



_DESIGNREGION_DEVICEUNDERTESTTYPE = _descriptor.EnumDescriptor(
  name='DeviceUnderTestType',
  full_name='bigspicy.DesignRegion.DeviceUnderTestType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUB_REGION', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODULE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EXTERNAL_MODULE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=694,
  serialized_end=764,
)
_sym_db.RegisterEnumDescriptor(_DESIGNREGION_DEVICEUNDERTESTTYPE)


_NET = _descriptor.Descriptor(
  name='Net',
  full_name='bigspicy.Net',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='signal_name', full_name='bigspicy.Net.signal_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index', full_name='bigspicy.Net.index', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=83,
)


_SIMULATEDDRIVER = _descriptor.Descriptor(
  name='SimulatedDriver',
  full_name='bigspicy.SimulatedDriver',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='net', full_name='bigspicy.SimulatedDriver.net', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=130,
)


_CAPACITIVELOAD = _descriptor.Descriptor(
  name='CapacitiveLoad',
  full_name='bigspicy.CapacitiveLoad',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='net', full_name='bigspicy.CapacitiveLoad.net', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_f', full_name='bigspicy.CapacitiveLoad.value_f', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=193,
)


_DCBIAS = _descriptor.Descriptor(
  name='DCBias',
  full_name='bigspicy.DCBias',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='net', full_name='bigspicy.DCBias.net', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=231,
)


_VOLTAGEPROBE = _descriptor.Descriptor(
  name='VoltageProbe',
  full_name='bigspicy.VoltageProbe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='net', full_name='bigspicy.VoltageProbe.net', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=275,
)


_ANALYSISPORT = _descriptor.Descriptor(
  name='AnalysisPort',
  full_name='bigspicy.AnalysisPort',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='net', full_name='bigspicy.AnalysisPort.net', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='load_capacitance_f', full_name='bigspicy.AnalysisPort.load_capacitance_f', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=347,
)


_DESIGNREGION = _descriptor.Descriptor(
  name='DesignRegion',
  full_name='bigspicy.DesignRegion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='bigspicy.DesignRegion.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dut_type', full_name='bigspicy.DesignRegion.dut_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='for_top_module', full_name='bigspicy.DesignRegion.for_top_module', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instances', full_name='bigspicy.DesignRegion.instances', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dc_biases', full_name='bigspicy.DesignRegion.dc_biases', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loads', full_name='bigspicy.DesignRegion.loads', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drivers', full_name='bigspicy.DesignRegion.drivers', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='voltage_probes', full_name='bigspicy.DesignRegion.voltage_probes', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ports', full_name='bigspicy.DesignRegion.ports', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DESIGNREGION_DEVICEUNDERTESTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=764,
)


_CIRCUITANALYSIS = _descriptor.Descriptor(
  name='CircuitAnalysis',
  full_name='bigspicy.CircuitAnalysis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='design_regions', full_name='bigspicy.CircuitAnalysis.design_regions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=766,
  serialized_end=831,
)

_SIMULATEDDRIVER.fields_by_name['net'].message_type = _NET
_CAPACITIVELOAD.fields_by_name['net'].message_type = _NET
_DCBIAS.fields_by_name['net'].message_type = _NET
_VOLTAGEPROBE.fields_by_name['net'].message_type = _NET
_ANALYSISPORT.fields_by_name['net'].message_type = _NET
_DESIGNREGION.fields_by_name['dut_type'].enum_type = _DESIGNREGION_DEVICEUNDERTESTTYPE
_DESIGNREGION.fields_by_name['dc_biases'].message_type = _DCBIAS
_DESIGNREGION.fields_by_name['loads'].message_type = _CAPACITIVELOAD
_DESIGNREGION.fields_by_name['drivers'].message_type = _SIMULATEDDRIVER
_DESIGNREGION.fields_by_name['voltage_probes'].message_type = _VOLTAGEPROBE
_DESIGNREGION.fields_by_name['ports'].message_type = _ANALYSISPORT
_DESIGNREGION_DEVICEUNDERTESTTYPE.containing_type = _DESIGNREGION
_CIRCUITANALYSIS.fields_by_name['design_regions'].message_type = _DESIGNREGION
DESCRIPTOR.message_types_by_name['Net'] = _NET
DESCRIPTOR.message_types_by_name['SimulatedDriver'] = _SIMULATEDDRIVER
DESCRIPTOR.message_types_by_name['CapacitiveLoad'] = _CAPACITIVELOAD
DESCRIPTOR.message_types_by_name['DCBias'] = _DCBIAS
DESCRIPTOR.message_types_by_name['VoltageProbe'] = _VOLTAGEPROBE
DESCRIPTOR.message_types_by_name['AnalysisPort'] = _ANALYSISPORT
DESCRIPTOR.message_types_by_name['DesignRegion'] = _DESIGNREGION
DESCRIPTOR.message_types_by_name['CircuitAnalysis'] = _CIRCUITANALYSIS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Net = _reflection.GeneratedProtocolMessageType('Net', (_message.Message,), {
  'DESCRIPTOR' : _NET,
  '__module__' : 'proto.circuit_analysis_pb2'
  # @@protoc_insertion_point(class_scope:bigspicy.Net)
  })
_sym_db.RegisterMessage(Net)

SimulatedDriver = _reflection.GeneratedProtocolMessageType('SimulatedDriver', (_message.Message,), {
  'DESCRIPTOR' : _SIMULATEDDRIVER,
  '__module__' : 'proto.circuit_analysis_pb2'
  # @@protoc_insertion_point(class_scope:bigspicy.SimulatedDriver)
  })
_sym_db.RegisterMessage(SimulatedDriver)

CapacitiveLoad = _reflection.GeneratedProtocolMessageType('CapacitiveLoad', (_message.Message,), {
  'DESCRIPTOR' : _CAPACITIVELOAD,
  '__module__' : 'proto.circuit_analysis_pb2'
  # @@protoc_insertion_point(class_scope:bigspicy.CapacitiveLoad)
  })
_sym_db.RegisterMessage(CapacitiveLoad)

DCBias = _reflection.GeneratedProtocolMessageType('DCBias', (_message.Message,), {
  'DESCRIPTOR' : _DCBIAS,
  '__module__' : 'proto.circuit_analysis_pb2'
  # @@protoc_insertion_point(class_scope:bigspicy.DCBias)
  })
_sym_db.RegisterMessage(DCBias)

VoltageProbe = _reflection.GeneratedProtocolMessageType('VoltageProbe', (_message.Message,), {
  'DESCRIPTOR' : _VOLTAGEPROBE,
  '__module__' : 'proto.circuit_analysis_pb2'
  # @@protoc_insertion_point(class_scope:bigspicy.VoltageProbe)
  })
_sym_db.RegisterMessage(VoltageProbe)

AnalysisPort = _reflection.GeneratedProtocolMessageType('AnalysisPort', (_message.Message,), {
  'DESCRIPTOR' : _ANALYSISPORT,
  '__module__' : 'proto.circuit_analysis_pb2'
  # @@protoc_insertion_point(class_scope:bigspicy.AnalysisPort)
  })
_sym_db.RegisterMessage(AnalysisPort)

DesignRegion = _reflection.GeneratedProtocolMessageType('DesignRegion', (_message.Message,), {
  'DESCRIPTOR' : _DESIGNREGION,
  '__module__' : 'proto.circuit_analysis_pb2'
  # @@protoc_insertion_point(class_scope:bigspicy.DesignRegion)
  })
_sym_db.RegisterMessage(DesignRegion)

CircuitAnalysis = _reflection.GeneratedProtocolMessageType('CircuitAnalysis', (_message.Message,), {
  'DESCRIPTOR' : _CIRCUITANALYSIS,
  '__module__' : 'proto.circuit_analysis_pb2'
  # @@protoc_insertion_point(class_scope:bigspicy.CircuitAnalysis)
  })
_sym_db.RegisterMessage(CircuitAnalysis)


# @@protoc_insertion_point(module_scope)
