# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/test_manifest.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/test_manifest.proto',
  package='bigspicy',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19proto/test_manifest.proto\x12\x08\x62igspicy\"j\n\x10\x44\x65layComputation\x12\x1b\n\x13spice_variable_name\x18\x01 \x01(\t\x12\x14\n\x0ctrigger_node\x18\x02 \x01(\t\x12\x13\n\x0btarget_node\x18\x03 \x01(\t\x12\x0e\n\x06result\x18\x04 \x01(\x01\"k\n\x0bMeasurement\x12\x13\n\x0btarget_node\x18\x01 \x01(\t\x12\x1b\n\x13spice_variable_name\x18\x02 \x01(\t\"*\n\x04Type\x12\x0b\n\x07VOLTAGE\x10\x00\x12\x0b\n\x07\x43URRENT\x10\x01\x12\x08\n\x04TIME\x10\x02\"\xc4\x03\n\x0eLinearAnalysis\x12\x19\n\x11spice_source_file\x18\x01 \x01(\t\x12\x1a\n\x12\x64\x65sign_region_name\x18\x02 \x01(\t\x12\x34\n\ranalysis_type\x18\x03 \x01(\x0e\x32\x1d.bigspicy.LinearAnalysis.Type\x12\x36\n\nsweep_type\x18\x04 \x01(\x0e\x32\".bigspicy.LinearAnalysis.SweepType\x12\x15\n\rstart_freq_hz\x18\x05 \x01(\x01\x12\x14\n\x0cstop_freq_hz\x18\x06 \x01(\x01\x12\x12\n\nnum_points\x18\x07 \x01(\x04\x12\x0c\n\x04tags\x18\x14 \x03(\t\x12,\n\x05ports\x18\x15 \x03(\x0b\x32\x1d.bigspicy.LinearAnalysis.Port\x1aG\n\x04Port\x12\x0e\n\x06number\x18\x01 \x01(\x04\x12\x0c\n\x04node\x18\x02 \x01(\t\x12!\n\x19generating_impedance_ohms\x18\x03 \x01(\x01\"\"\n\x04Type\x12\x05\n\x01Y\x10\x00\x12\x05\n\x01Z\x10\x01\x12\x05\n\x01S\x10\x02\x12\x05\n\x01H\x10\x03\"#\n\tSweepType\x12\n\n\x06LINEAR\x10\x00\x12\n\n\x06\x44\x45\x43\x41\x44\x45\x10\x01\"\xd2\x01\n\x11TransientAnalysis\x12\x19\n\x11spice_source_file\x18\x01 \x01(\t\x12\x1a\n\x12\x64\x65sign_region_name\x18\x02 \x01(\t\x12\x13\n\x0bmodule_name\x18\x03 \x01(\t\x12+\n\x0cmeasurements\x18\x0b \x03(\x0b\x32\x15.bigspicy.Measurement\x12\x36\n\x12\x64\x65lay_computations\x18\x0c \x03(\x0b\x32\x1a.bigspicy.DelayComputation\x12\x0c\n\x04tags\x18\x14 \x03(\t\"z\n\x0cTestManifest\x12\x37\n\x12transient_analyses\x18\x01 \x03(\x0b\x32\x1b.bigspicy.TransientAnalysis\x12\x31\n\x0flinear_analyses\x18\x02 \x03(\x0b\x32\x18.bigspicy.LinearAnalysisb\x06proto3'
)



_MEASUREMENT_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='bigspicy.Measurement.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VOLTAGE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CURRENT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TIME', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=212,
  serialized_end=254,
)
_sym_db.RegisterEnumDescriptor(_MEASUREMENT_TYPE)

_LINEARANALYSIS_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='bigspicy.LinearAnalysis.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Y', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Z', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='S', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='H', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=638,
  serialized_end=672,
)
_sym_db.RegisterEnumDescriptor(_LINEARANALYSIS_TYPE)

_LINEARANALYSIS_SWEEPTYPE = _descriptor.EnumDescriptor(
  name='SweepType',
  full_name='bigspicy.LinearAnalysis.SweepType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LINEAR', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DECADE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=674,
  serialized_end=709,
)
_sym_db.RegisterEnumDescriptor(_LINEARANALYSIS_SWEEPTYPE)


_DELAYCOMPUTATION = _descriptor.Descriptor(
  name='DelayComputation',
  full_name='bigspicy.DelayComputation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='spice_variable_name', full_name='bigspicy.DelayComputation.spice_variable_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trigger_node', full_name='bigspicy.DelayComputation.trigger_node', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_node', full_name='bigspicy.DelayComputation.target_node', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='bigspicy.DelayComputation.result', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=145,
)


_MEASUREMENT = _descriptor.Descriptor(
  name='Measurement',
  full_name='bigspicy.Measurement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_node', full_name='bigspicy.Measurement.target_node', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spice_variable_name', full_name='bigspicy.Measurement.spice_variable_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MEASUREMENT_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=254,
)


_LINEARANALYSIS_PORT = _descriptor.Descriptor(
  name='Port',
  full_name='bigspicy.LinearAnalysis.Port',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='bigspicy.LinearAnalysis.Port.number', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node', full_name='bigspicy.LinearAnalysis.Port.node', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='generating_impedance_ohms', full_name='bigspicy.LinearAnalysis.Port.generating_impedance_ohms', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=565,
  serialized_end=636,
)

_LINEARANALYSIS = _descriptor.Descriptor(
  name='LinearAnalysis',
  full_name='bigspicy.LinearAnalysis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='spice_source_file', full_name='bigspicy.LinearAnalysis.spice_source_file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='design_region_name', full_name='bigspicy.LinearAnalysis.design_region_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='analysis_type', full_name='bigspicy.LinearAnalysis.analysis_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sweep_type', full_name='bigspicy.LinearAnalysis.sweep_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_freq_hz', full_name='bigspicy.LinearAnalysis.start_freq_hz', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stop_freq_hz', full_name='bigspicy.LinearAnalysis.stop_freq_hz', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_points', full_name='bigspicy.LinearAnalysis.num_points', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tags', full_name='bigspicy.LinearAnalysis.tags', index=7,
      number=20, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ports', full_name='bigspicy.LinearAnalysis.ports', index=8,
      number=21, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_LINEARANALYSIS_PORT, ],
  enum_types=[
    _LINEARANALYSIS_TYPE,
    _LINEARANALYSIS_SWEEPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=709,
)


_TRANSIENTANALYSIS = _descriptor.Descriptor(
  name='TransientAnalysis',
  full_name='bigspicy.TransientAnalysis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='spice_source_file', full_name='bigspicy.TransientAnalysis.spice_source_file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='design_region_name', full_name='bigspicy.TransientAnalysis.design_region_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='module_name', full_name='bigspicy.TransientAnalysis.module_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='measurements', full_name='bigspicy.TransientAnalysis.measurements', index=3,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delay_computations', full_name='bigspicy.TransientAnalysis.delay_computations', index=4,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tags', full_name='bigspicy.TransientAnalysis.tags', index=5,
      number=20, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=712,
  serialized_end=922,
)


_TESTMANIFEST = _descriptor.Descriptor(
  name='TestManifest',
  full_name='bigspicy.TestManifest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='transient_analyses', full_name='bigspicy.TestManifest.transient_analyses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='linear_analyses', full_name='bigspicy.TestManifest.linear_analyses', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=924,
  serialized_end=1046,
)

_MEASUREMENT_TYPE.containing_type = _MEASUREMENT
_LINEARANALYSIS_PORT.containing_type = _LINEARANALYSIS
_LINEARANALYSIS.fields_by_name['analysis_type'].enum_type = _LINEARANALYSIS_TYPE
_LINEARANALYSIS.fields_by_name['sweep_type'].enum_type = _LINEARANALYSIS_SWEEPTYPE
_LINEARANALYSIS.fields_by_name['ports'].message_type = _LINEARANALYSIS_PORT
_LINEARANALYSIS_TYPE.containing_type = _LINEARANALYSIS
_LINEARANALYSIS_SWEEPTYPE.containing_type = _LINEARANALYSIS
_TRANSIENTANALYSIS.fields_by_name['measurements'].message_type = _MEASUREMENT
_TRANSIENTANALYSIS.fields_by_name['delay_computations'].message_type = _DELAYCOMPUTATION
_TESTMANIFEST.fields_by_name['transient_analyses'].message_type = _TRANSIENTANALYSIS
_TESTMANIFEST.fields_by_name['linear_analyses'].message_type = _LINEARANALYSIS
DESCRIPTOR.message_types_by_name['DelayComputation'] = _DELAYCOMPUTATION
DESCRIPTOR.message_types_by_name['Measurement'] = _MEASUREMENT
DESCRIPTOR.message_types_by_name['LinearAnalysis'] = _LINEARANALYSIS
DESCRIPTOR.message_types_by_name['TransientAnalysis'] = _TRANSIENTANALYSIS
DESCRIPTOR.message_types_by_name['TestManifest'] = _TESTMANIFEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DelayComputation = _reflection.GeneratedProtocolMessageType('DelayComputation', (_message.Message,), {
  'DESCRIPTOR' : _DELAYCOMPUTATION,
  '__module__' : 'proto.test_manifest_pb2'
  # @@protoc_insertion_point(class_scope:bigspicy.DelayComputation)
  })
_sym_db.RegisterMessage(DelayComputation)

Measurement = _reflection.GeneratedProtocolMessageType('Measurement', (_message.Message,), {
  'DESCRIPTOR' : _MEASUREMENT,
  '__module__' : 'proto.test_manifest_pb2'
  # @@protoc_insertion_point(class_scope:bigspicy.Measurement)
  })
_sym_db.RegisterMessage(Measurement)

LinearAnalysis = _reflection.GeneratedProtocolMessageType('LinearAnalysis', (_message.Message,), {

  'Port' : _reflection.GeneratedProtocolMessageType('Port', (_message.Message,), {
    'DESCRIPTOR' : _LINEARANALYSIS_PORT,
    '__module__' : 'proto.test_manifest_pb2'
    # @@protoc_insertion_point(class_scope:bigspicy.LinearAnalysis.Port)
    })
  ,
  'DESCRIPTOR' : _LINEARANALYSIS,
  '__module__' : 'proto.test_manifest_pb2'
  # @@protoc_insertion_point(class_scope:bigspicy.LinearAnalysis)
  })
_sym_db.RegisterMessage(LinearAnalysis)
_sym_db.RegisterMessage(LinearAnalysis.Port)

TransientAnalysis = _reflection.GeneratedProtocolMessageType('TransientAnalysis', (_message.Message,), {
  'DESCRIPTOR' : _TRANSIENTANALYSIS,
  '__module__' : 'proto.test_manifest_pb2'
  # @@protoc_insertion_point(class_scope:bigspicy.TransientAnalysis)
  })
_sym_db.RegisterMessage(TransientAnalysis)

TestManifest = _reflection.GeneratedProtocolMessageType('TestManifest', (_message.Message,), {
  'DESCRIPTOR' : _TESTMANIFEST,
  '__module__' : 'proto.test_manifest_pb2'
  # @@protoc_insertion_point(class_scope:bigspicy.TestManifest)
  })
_sym_db.RegisterMessage(TestManifest)


# @@protoc_insertion_point(module_scope)
